# Comment that will be sent if an issue is judged to be closed
comment: |
  Whoops, it looks like you created an issue without filling out the checklist and providing all the needed information from one of the issue templates: <https://github.com/Homebrew/homebrew-core/issues/new/choose>

  As we need all this information to help you we're closing this issue. If you add the necessary information to this issue (**don't create a new or duplicate issue, please**) and comment to let us know, a Homebrew maintainer will check it out when they get the chance. If it's deemed to be a valid issue then this issue may be reopened.

  Sorry!
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# reproducible bug report
  - "are reporting a bug others will be able to reproduce"
  - "have a problem with "
  - "brew update"
  - "brew doctor"
  - "brew gist-logs"
  - "brew config"
  - "brew doctor"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: false
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
